### ISSUE TITLE
make编译grpc报错

### ISSUE THREAD

**Issue by 2473o** [xuperchain/xbench#43]
报错如下
```
deployment@depolyment-virtual-machine:~/xuperchain/xbench-master$ make
sh script/build.sh
# github.com/bojand/ghz/runner
../../go/pkg/mod/github.com/bojand/ghz@v0.94.0/runner/requester.go:336:28: undefined: grpc.WithBalancerName
```
系统环境
```
deployment@depolyment-virtual-machine:~/xuperchain/xbench-master$ more /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Go 环境
```
deployment@depolyment-virtual-machine:~/xuperchain/xbench-master$ go version
go version go1.18.1 linux/amd64
deployment@depolyment-virtual-machine:~/xuperchain/xbench-master$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/deployment/.cache/go-build"
GOENV="/home/deployment/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/deployment/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/deployment/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/lib/go-1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.18/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.1"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/deployment/xuperchain/xbench-master/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3233518727=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by 2473o** [comment]
补充，用的master分支

**Comment by godeamon** [comment]
@2473o 你好，这个问题是 go 版本问题，go 1.18.x 版本先在本地将 github.com/bojand/ghz v0.94.0 升级到 github.com/bojand/ghz v0.117.0 然后编译，后续我们更新下或者你这边方便也可以贡献代码。

**Comment by 2473o** [comment]
用docker编译成功了
```
deployment@depolyment-virtual-machine:~/xbench$ cat docker-compose.yml 
version: "3"
services: 
  compile:
    image: golang:1.18
    container_name: xbench_compile
    tty: true
    volumes:
      - ./xbench-master:/home/
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn
```
